### ISSUE TITLE
Great Job - perfect for learning how nwjs works.

### ISSUE THREAD

**Issue by gbucas** [RIAEvangelist/nwjs-browser-framework#2]
Thanks for doing this - GREAT JOB!

Downloaded it and had it working on Windows 10 within a few minutes.

Seems to work perfectly except the "Options" button (on right-hand side of the address bar).
But I am sure I can fix that (or add functionality to that button if it wasn't intended to have any yet).

Great building block for developing web-based apps - will dramatically cut learning curve for anyone getting started with nwjs (like me)! 

Duly impressed...!

Regards

Gerard

**Comment by RIAEvangelist** [comment]
:+1:
